### ISSUE TITLE
blivet-gui should not crash when an invalid disk configuration is found

### ISSUE THREAD

**Issue by lantw44** [rhinstaller/blivet-gui#13]
This problem was reported to blivet: https://github.com/rhinstaller/blivet/issues/288

It will be nice if blivet-gui can ignore invalid disks instead of crashing or hanging. Details of this bug is already provided in the blivet bug report.

**Comment by vojtechtrefny** [comment]
With d0be47fe837f6ca639e11544d07ebc4c0aeb2fe0 blivet-gui is now able to skip disk with broken/invalid/unknown disklabel. W
