### ISSUE TITLE
Crazy idea: creation of an official blivet-gui only distribution, "à la Gparted"

### ISSUE THREAD

**Issue by q2dg** [rhinstaller/blivet-gui#25]
This shouldn't be much difficult with the right kickstart file and the livecd-creator tool... It should have a light desktop (Openbox or similar) and all the needed command-line tools

I think this would give a lot more visibility to this project towards the community (I'm thinking in distrowatch, etc)

**Comment by vojtechtrefny** [comment]
It isn't a crazy idea, but it might be hard to actually "support" the distribution. It's not just creating the ISO, but I'd have to deal with bugs/issues of every package on the ISO.

It's probably a better idea to make blivet-gui part of the "normal" Fedora Live DVD.

**Comment by q2dg** [comment]
Ok. Do you know which would be the procedure to achieve what you say? If you tell me the place to ask for it, I will do it.

**Comment by vojtechtrefny** [comment]
We have started working on adding blivet-gui to Anaconda as an alternative partitioning tool. This will also result in adding blivet-gui package to Live DVDs.

https://fedoraproject.org/wiki/Changes/AnacondaBlivetGUI
