### ISSUE TITLE
Installation media is visible in Blivet GUI

### ISSUE THREAD

**Issue by M4rtinK** [rhinstaller/blivet-gui#53]
Installation media (in this case a recent F26 netinst image loaded on a USB flash drive with FMW) is visible and can be manipulated in Blivet GUI. Interestingly, the installation media is not visible in the storage spoke.

**Comment by M4rtinK** [comment]
Looks like clicking "refresh" on storage spoke makes the installation media vanish in Blivet GUI spoke.

**Comment by vojtechtrefny** [comment]
#64 fixes this
