### ISSUE TITLE
Installation via pip is broken

### ISSUE THREAD

**Issue by osmoc** [rhinstaller/blivet-gui#70]
The installation via pip seems to be successful:
pip3 install --user -e ./
Installing collected packages: blivet-gui
  Found existing installation: blivet-gui 2.1.4
    Uninstalling blivet-gui-2.1.4:
      Successfully uninstalled blivet-gui-2.1.4
  Running setup.py develop for blivet-gui
Successfully installed blivet-gui

But the resulting script in ~/.local.bin/ fails to run:
blivet-gui
Traceback (most recent call last):
  File "/home/max/.local/bin/blivet-gui", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/max/source/blivet-gui/blivet-gui", line 40, in <module>
    from blivetgui.dialogs.message_dialogs import ErrorDialog
  File "/home/max/source/blivet-gui/blivetgui/dialogs/message_dialogs.py", line 31, in <module>
    from .helpers import adjust_scrolled_size
  File "/home/max/source/blivet-gui/blivetgui/dialogs/helpers.py", line 34, in <module>
    from blivet import devicefactory, formats
ImportError: No module named 'blivet'

**Comment by vojtechtrefny** [comment]
The error simply means that you don't have blivet module.

I don't plan to support installation using pip -- blivet depends on some C libraries and it is not possible to install these using pip, so it won't be possible to install blivet-gui without these dependencies.
